"""``leash scan openclaw`` — explain what an OpenClaw agent can do and what your policy allows.

Works offline: it reads Leash's built-in OpenClaw tool catalog and evaluates
your local policy files the same way the server does.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import yaml

from app.policy.catalog import OPENCLAW_TOOLS
from app.policy.engine import _match_action, _match_agent
from app.policy.simple import expand, render

RISK_ICON = {"high": "🔴", "medium": "🟠", "low": "🟢"}


def _load(policies_dir: Path) -> list[tuple[Path, dict]]:
    out: list[tuple[Path, dict]] = []
    for f in sorted(policies_dir.glob("*.y*ml")):
        try:
            doc = expand(yaml.safe_load(f.read_text()))
        except yaml.YAMLError:
            continue
        if isinstance(doc, dict):
            out.append((f, doc))
    out.sort(key=lambda pd: pd[1].get("priority", 0), reverse=True)
    return out


def decide(policies: list[tuple[Path, dict]], agent_name: str, tool: str) -> dict[str, Any]:
    """First-match evaluation of *tool* for *agent_name* (ignores resource/condition rules)."""
    for path, policy in policies:
        if not _match_agent(policy, "", agent_name):
            continue
        for rule in policy.get("rules", []):
            if not _match_action(rule.get("action", ""), tool):
                continue
            if rule.get("resource") or rule.get("conditions"):
                continue
            effect = rule.get("effect", "deny")
            if effect == "deny" and policy.get("mode") == "observe":
                effect = "observe"
            return {"effect": effect, "policy": policy.get("name"), "file": path, "rule": rule.get("action")}
    return {"effect": "deny", "policy": None, "file": None, "rule": None}


def scan_openclaw(agent_name: str = "openclaw-agent", fmt: str = "table",
                  save_policy: str | None = None, policies_dir: str | None = None) -> int:
    from app.core.config import POLICIES_DIR

    pdir = Path(policies_dir or POLICIES_DIR)
    policies = _load(pdir)
    rows = []
    for tool, info in OPENCLAW_TOOLS.items():
        d = decide(policies, agent_name, tool)
        rows.append({"tool": tool, **{k: info[k] for k in ("group", "risk", "does")}, **d})

    if save_policy:
        settings = {r["tool"]: ("deny" if r["effect"] == "observe" else r["effect"]) for r in rows}
        header = "# OpenClaw policy generated by `leash scan openclaw`. Edit any line, then save.\n"
        Path(save_policy).write_text(render("openclaw", settings, header=header))

    if fmt == "json":
        for r in rows:
            r["file"] = str(r["file"]) if r["file"] else None
        print(json.dumps({"agent": agent_name, "tools": rows}, indent=2))
        return 0

    tty = sys.stdout.isatty() and not os.getenv("NO_COLOR")
    g, r_, y, d, b, x = (("\033[32m", "\033[31m", "\033[33m", "\033[2m", "\033[1m", "\033[0m")
                         if tty else ("",) * 6)
    def rel(p: Path) -> str:
        try:
            return str(p.resolve().relative_to(Path.cwd()))
        except ValueError:
            return str(p)

    files = sorted({rel(r["file"]) for r in rows if r["file"]})
    print(f"\n  {b}What can OpenClaw do?{x}  {d}({len(rows)} tools, from Leash's OpenClaw catalog){x}")
    print(f"  Agent name: {agent_name}    Policy: {', '.join(files) or f'{d}none matched — everything is denied{x}'}\n")

    group = None
    for r in rows:
        if r["group"] != group:
            group = r["group"]
            print(f"  {b}{group}{x}")
        label = {"allow": f"{g}✔ allow{x}", "deny": f"{r_}✘ deny {x}", "observe": f"{y}◉ watch{x}"}[r["effect"]]
        warn = f"  {y}⚠ high risk and allowed{x}" if r["risk"] == "high" and r["effect"] == "allow" else ""
        print(f"    {RISK_ICON[r['risk']]} {r['tool']:<17} {label}   {d}can {r['does']}{x}{warn}")

    def count(risk: str) -> str:
        sel = [r for r in rows if r["risk"] == risk]
        return f"{len(sel)} {risk}-risk ({sum(r['effect'] == 'allow' for r in sel)} allowed)"

    print(f"\n  {count('high')} · {count('medium')} · {count('low')}")
    target = files[0] if files else rel(pdir / "openclaw.yaml")
    print(f"\n  To change one: edit {b}{target}{x}, e.g. {d}exec: deny{x} → {d}exec: allow{x}. Leash reloads it instantly.")
    if save_policy:
        print(f"  {g}✔{x} Wrote a policy with these settings to {save_policy}")
    print()
    return 0
